### ISSUE TITLE
[AVM Module Issue]: subnet delegation actions missing in root variable file

### ISSUE THREAD

**Issue by pieter-jangoeman** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#121]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.1

### Description

It seems that in the variable file in the subnets module, there is an option to optionally give a service_delegation both a name and an action, but in the root variables file, there's only the option to give it a name, the action parameter seems to be missing.
It does seem needed, but in the code of the subnet module, I can't find it to be used as well..

**Comment by jaredfholgate** [comment]
You are correct that the `actions` was erroneously added to the subnet module variables. It is a read-only attribute. Removing it from the variables in this PR: #152
