### ISSUE TITLE
[AVM Module Issue]: inconsistant use of variable types for bool/strings

### ISSUE THREAD

**Issue by pieter-jangoeman** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#122]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.1

### Description

Hi,

I noticed two parameters in the subnet part that are just below each other, and have similar values, but different types.
I'm talking about these two: 

`privateEndpointNetworkPolicies    = var.private_endpoint_network_policies`
`privateLinkServiceNetworkPolicies = var.private_link_service_network_policies_enabled == false ? "Disabled" : "Enabled"``

private_endpoint_network_policies is a string, 
private_link_service_network_policies_enabled is a bool

While they both end up in a string which is "Disabled" or "Enabled". only the bool needs to be translated first.

A consensus should be made on using OR a bool, OR a string, to make it clear.

Possibly there are other variables in the same case, but didn't check them all.

Thanks.

**Comment by jaredfholgate** [comment]
I'm unsure about this. 

- `privateEndpointNetworkPolicies` has the possible inputs: `Disabled`,`Enabled`,`NetworkSecurityGroupEnabled` or `RouteTableEnabled`
- `privateLinkServiceNetworkPolicies` has the possible inputs: `Disabled` or `Enabled`

I think we should leave it as it is for now given this. If at a later date `privateLinkServiceNetworkPolicies` gains more input options, then we can update accordingly. At the moment it makes sense for it to be a bool from a usability perspective. This follows the same pattern as the azurerm resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#argument-reference

**Comment by pieter-jangoeman** [comment]
Hi Jared,

it seems that I missed that :)  in that case your solution does sound like
a good plan, apologies!
Keep up the good work!

Pieter-Jan

Op vr 11 okt 2024 om 11:26 schreef Jared Holgate ***@***.***>:
