### ISSUE TITLE
[AVM Module Issue]: azurerm 4 compatibility

### ISSUE THREAD

**Issue by Laffs2k5** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#146]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.4.0

### Description

Hi,

This modules current version constraints on the azurem provider prevents me from upgrading my terraform project.
Please issue an updated release with support for azurerm `4.x`.

Thanks :-)

**Comment by But4ler** [comment]
Hello
The problem of version fragmentation is really important on AVM, and it sometimes affects modules like random 
https://github.com/Azure/Azure-Verified-Modules/issues/1576#issuecomment-2439915022

**Comment by chanstev** [comment]
We need to consume AzureRM >=4.6, the ~> 3.71  is blocking us to use AVM networking module.
