### ISSUE TITLE
[AVM Question/Feedback]: Using create_reverse_vnet_peering for a VNet in a different subscription

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#162]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

It's brilliant to have the 'create_reverse_vnet_peering' option but as I understand it only works if the VNets are in the same subscription/under the same tf provider.

Is there any information how we could make this work for VNets across subscriptions?

**Comment by jaredfholgate** [comment]
> ### Check for previous/existing GitHub issues
> * [x]  I have checked for previous/existing GitHub issues
> 
> ### Description
> It's brilliant to have the 'create_reverse_vnet_peering' option but as I understand it only works if the VNets are in the same subscription/under the same tf provider.
> 
> Is there any information how we could make this work for VNets across subscriptions?

Hi. This will work across subscriptions provided the principal running the apply has access to both.

The `virtual_network.resource_id` and `remote_virtual_network.resource_id` can be for any subscription. This is for a direct submodule call where you have existing virtual networks: https://registry.terraform.io/modules/Azure/avm-res-network-virtualnetwork/azurerm/latest/submodules/peering

For the creating a new virtual network, just supply the `remote_virtual_network_resource_id`.

We use the AzAPI provider which does not have the restriction on a single subscription like the azurerm provider.

**Comment by captainhook** [comment]
Thanks, Jared. I ran the apply from my local machine which had User Access Administrator role at the time so it should have deployed the remote peering but it doesn't seem to have. I'll try again in the next few days and report back.

**Comment by jaredfholgate** [comment]
> Thanks, Jared. I ran the apply from my local machine which had User Access Administrator role at the time so it should have deployed the remote peering but it doesn't seem to have. I'll try again in the next few days and report back.

Hi. I'm not sure how the User Access Administrator role would be relevant here? It would need access to update the virtual network in both local and remote subscription for the peering.

If you have an error message to share, that would be useful.
