### ISSUE TITLE
[AVM Module Issue]: irrelevant plan changes after upgrading to terraform-azurerm-avm-res-network-virtualnetwork 0.6.0-0.7.1

### ISSUE THREAD

**Issue by oocx** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#173]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.6.0, 0.7.0, 0.7.1

### Description

With the upgrade to azapi v2, we now often see additional changes in our terraform plans because of changed etags, for example:

```hcl
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.buildagents_network.module.vnet.azapi_resource.vnet has changed
  ~ resource "azapi_resource" "vnet" {
        id                        = "/subscriptions/foo/resourceGroups/bar/providers/Microsoft.Network/virtualNetworks/buildagents-vnet-int-gwc"
        name                      = "foo"
      ~ output                    = {
          ~ etag       = "W/\"86ce7375-057d-4693-93b3-2200f28a1cf6\"" -> "W/\"4398a287-48b4-4d84-ae2b-5d7d1aa6c8eb\""
            id         = "/subscriptions/foo/resourceGroups/foo/Microsoft.Network/virtualNetworks/bar"
          ~ properties = {
              ~ subnets                = [
                  ~ {
                      ~ etag       = "W/\"86ce7375-057d-4693-93b3-2200f28a1cf6\"" -> "W/\"4398a287-48b4-4d84-ae2b-5d7d1aa6c8eb\""
                      ~ properties = {
                          ~ ipConfigurations  = [
                                {},
                              + {},
                              + {},
                            ]
                          ~ privateEndpoints  = [
                                {},
                              + {},
                            ]
                        }
                    },
                  ~ {
                      ~ etag       = "W/\"86ce7375-057d-4693-93b3-2200f28a1cf6\"" -> "W/\"4398a287-48b4-4d84-ae2b-5d7d1aa6c8eb\""
                      ~ properties = {
                          ~ ipConfigurations  = [
                                {},
                              + {},
                              + {},
                              + {},
                              + {},
                              + {},
                            ]
                        }
                    },
                ]
              ~ virtualNetworkPeerings = [
                  ~ {
                      ~ etag       = "W/\"86ce7375-057d-4693-93b3-2200f28a1cf6\"" -> "W/\"4398a287-48b4-4d84-ae2b-5d7d1aa6c8eb\""
                    },
                ]
            }        
```

There seems to be no way to ignore these changes, and they just clutter our terraform plans and make it harder to see real changes. These changes should not be visible by default, or there should at least be a way to disable getting those changes in our plans.

**Comment by jaredfholgate** [comment]
We can use the https://registry.terraform.io/providers/azure/azapi/latest/docs/resources/resource#response_export_values-1 to only export the things we care about. Will add it to the backlog. At the moment this is not causing the plan to make any changes, so not urgent.

**Comment by xzrians** [comment]
I'm not sure whether this one related or not. but every time plan,apply  it detect changes, delete the routing. need to apply again to attach the route table

```
Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # module.rg["network"].azurerm_resource_group.this has changed
  ~ resource "azurerm_resource_group" "this" {
        id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg"
        name       = "sea-prod-crawler-network-rg"
      + tags       = {}
        # (2 unchanged attributes hidden)
    }

  # module.routetable["crawler"].azurerm_route_table.this has changed
  ~ resource "azurerm_route_table" "this" {
        id                            = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"     
        name                          = "sea-prod-crawler-rt"
      ~ route                         = [
          + {
              + address_prefix         = "0.0.0.0/0"
              + name                   = "to-internet"
              + next_hop_in_ip_address = "172.16.0.4"
              + next_hop_type          = "VirtualAppliance"
            },
          + {
              + address_prefix         = "10.241.44.0/24"
              + name                   = "to-kvdc-dosm"
              + next_hop_in_ip_address = "172.16.0.4"
              + next_hop_type          = "VirtualAppliance"
            },
          + {
              + address_prefix         = "172.16.0.0/22"
              + name                   = "to-internal"
              + next_hop_in_ip_address = "172.16.0.4"
              + next_hop_type          = "VirtualAppliance"
            },
        ]
      ~ subnets                       = [
          + "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet",
        ]
      + tags                          = {}
        # (4 unchanged attributes hidden)
    }

  # module.virtualnetwork["sea-prod-crawler-vnet"].azapi_resource.vnet has changed
  ~ resource "azapi_resource" "vnet" {
        id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet"   
        name                      = "sea-prod-crawler-vnet"
      ~ output                    = {
          ~ etag       = "W/\"adeb012b-b869-435d-b191-b1ceb82f9bb2\"" -> "W/\"749db650-465f-4831-bd51-254baf47ed10\""
            id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet"
          ~ properties = {
              + subnets                = [
                  + {
                      + etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
                      + properties = {
                          + provisioningState = "Succeeded"
                        }
                    },
                ]
              + virtualNetworkPeerings = [
                  + {
                      + etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
                      + properties = {
                          + provisioningState                = "Succeeded"
                          + remoteAddressSpace               = {
                              + addressPrefixes = [
                                  + "172.16.0.0/24",
                                ]
                            }
                          + remoteVirtualNetworkAddressSpace = {
                              + addressPrefixes = [
                                  + "172.16.0.0/24",
                                ]
                            }
                          + resourceGuid                     = "b2ab1dc0-0b02-0b0a-2aa6-6be86007414e"
                        }
                    },
                ]
                # (4 unchanged attributes hidden)
            }
            tags       = {
                deployed_by = "terraform"
                environment = "production"
            }
            # (1 unchanged attribute hidden)
        }
        tags                      = {
            "deployed_by" = "terraform"
            "environment" = "production"
        }
        # (7 unchanged attributes hidden)
    }

  # module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet has changed
  ~ resource "azapi_resource" "subnet" {
      ~ body                      = {
          ~ properties = {
              ~ routeTable                        = null -> {
                  + id = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"
                }
                # (11 unchanged attributes hidden)
            }
        }
        id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
        name                      = "sea-prod-crawler-subnet"
      ~ output                    = {
          ~ etag       = "W/\"f5b2b34e-98be-440e-b523-496805063efa\"" -> "W/\"749db650-465f-4831-bd51-254baf47ed10\""
            id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
            # (2 unchanged attributes hidden)
        }
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.      

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # module.routetable["crawler"].data.azurerm_client_config.telemetry[0] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_client_config" "telemetry" {
      + client_id       = (known after apply)
      + id              = (known after apply)
      + object_id       = (known after apply)
      + subscription_id = (known after apply)
      + tenant_id       = (known after apply)
    }

  # module.routetable["crawler"].data.modtm_module_source.telemetry[0] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "modtm_module_source" "telemetry" {
      + module_path    = ".terraform/modules/routetable"
      + module_source  = (known after apply)
      + module_version = (known after apply)
    }

  # module.routetable["crawler"].azurerm_route_table.this will be updated in-place
  ~ resource "azurerm_route_table" "this" {
      ~ bgp_route_propagation_enabled = true -> false
        id                            = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"     
        name                          = "sea-prod-crawler-rt"
        tags                          = {}
        # (5 unchanged attributes hidden)
    }

  # module.routetable["crawler"].modtm_telemetry.telemetry[0] will be updated in-place
  ~ resource "modtm_telemetry" "telemetry" {
      + ephemeral_number = (known after apply)
        id               = "8cba77cc-8301-41f9-9d5f-f39303488427"
      + nonce            = (known after apply)
      ~ tags             = {
          ~ "module_source"   = "registry.terraform.io/Azure/avm-res-network-routetable/azurerm" -> (known after apply)
          ~ "module_version"  = "0.3.1" -> (known after apply)
            "random_id"       = "50b0928b-28ed-4bff-28df-d43508293e3d"
          ~ "subscription_id" = "subs" -> (known after apply)
          ~ "tenant_id"       = "tenant" -> (known after apply)
        }
    }

  # module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet will be updated in-place
  ~ resource "azapi_resource" "subnet" {
      ~ body                      = {
          ~ properties = {
              ~ routeTable                        = {
                  - id = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"
                } -> null
                # (11 unchanged attributes hidden)
            }
        }
        id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
        name                      = "sea-prod-crawler-subnet"
      ~ output                    = {
          - etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
          - id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
          - properties = {
              - provisioningState = "Succeeded"
            }
          - type       = "Microsoft.Network/virtualNetworks/subnets"
        } -> (known after apply)
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet: Modifying... [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet]
module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet: Modifications complete after 6s [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet]
module.routetable["crawler"].data.azurerm_client_config.telemetry[0]: Reading...
module.routetable["crawler"].data.modtm_module_source.telemetry[0]: Reading...
module.routetable["crawler"].data.azurerm_client_config.telemetry[0]: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD1kMTQ4MTM4NS05YzJkLTRmY2YtYjEwNy0zNmJkMzdlZDgxMGQ7b2JqZWN0SWQ9NWI4Zjg3YjctYTMwYy00ZGU0LWFjMzUtYzdjOTdhZDg5NTk0O3N1YnNjcmlwdGlvbklkPTRmNTc4ZTdmLWY1ZGMtNGQxZi05MDkyLWQ3NDkwZGFhNzM0Mzt0ZW5hbnRJZD0zNzNlOTBkMi1kOWEzLTQzYjUtODMyZS1jOGU5ODQ3YTc5Zjg=]
module.routetable["crawler"].azurerm_route_table.this: Modifying... [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt]
module.routetable["crawler"].data.modtm_module_source.telemetry[0]: Read complete after 0s
module.routetable["crawler"].azurerm_route_table.this: Modifications complete after 4s [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt]
```

**Comment by xzrians** [comment]
> I'm not sure whether this one related or not. but every time plan,apply it detect changes, delete the routing. need to apply again to attach the route table
> 
> ```
> Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:
> 
>   # module.rg["network"].azurerm_resource_group.this has changed
>   ~ resource "azurerm_resource_group" "this" {
>         id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg"
>         name       = "sea-prod-crawler-network-rg"
>       + tags       = {}
>         # (2 unchanged attributes hidden)
>     }
> 
>   # module.routetable["crawler"].azurerm_route_table.this has changed
>   ~ resource "azurerm_route_table" "this" {
>         id                            = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"     
>         name                          = "sea-prod-crawler-rt"
>       ~ route                         = [
>           + {
>               + address_prefix         = "0.0.0.0/0"
>               + name                   = "to-internet"
>               + next_hop_in_ip_address = "172.16.0.4"
>               + next_hop_type          = "VirtualAppliance"
>             },
>           + {
>               + address_prefix         = "10.241.44.0/24"
>               + name                   = "to-kvdc-dosm"
>               + next_hop_in_ip_address = "172.16.0.4"
>               + next_hop_type          = "VirtualAppliance"
>             },
>           + {
>               + address_prefix         = "172.16.0.0/22"
>               + name                   = "to-internal"
>               + next_hop_in_ip_address = "172.16.0.4"
>               + next_hop_type          = "VirtualAppliance"
>             },
>         ]
>       ~ subnets                       = [
>           + "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet",
>         ]
>       + tags                          = {}
>         # (4 unchanged attributes hidden)
>     }
> 
>   # module.virtualnetwork["sea-prod-crawler-vnet"].azapi_resource.vnet has changed
>   ~ resource "azapi_resource" "vnet" {
>         id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet"   
>         name                      = "sea-prod-crawler-vnet"
>       ~ output                    = {
>           ~ etag       = "W/\"adeb012b-b869-435d-b191-b1ceb82f9bb2\"" -> "W/\"749db650-465f-4831-bd51-254baf47ed10\""
>             id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet"
>           ~ properties = {
>               + subnets                = [
>                   + {
>                       + etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
>                       + properties = {
>                           + provisioningState = "Succeeded"
>                         }
>                     },
>                 ]
>               + virtualNetworkPeerings = [
>                   + {
>                       + etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
>                       + properties = {
>                           + provisioningState                = "Succeeded"
>                           + remoteAddressSpace               = {
>                               + addressPrefixes = [
>                                   + "172.16.0.0/24",
>                                 ]
>                             }
>                           + remoteVirtualNetworkAddressSpace = {
>                               + addressPrefixes = [
>                                   + "172.16.0.0/24",
>                                 ]
>                             }
>                           + resourceGuid                     = "b2ab1dc0-0b02-0b0a-2aa6-6be86007414e"
>                         }
>                     },
>                 ]
>                 # (4 unchanged attributes hidden)
>             }
>             tags       = {
>                 deployed_by = "terraform"
>                 environment = "production"
>             }
>             # (1 unchanged attribute hidden)
>         }
>         tags                      = {
>             "deployed_by" = "terraform"
>             "environment" = "production"
>         }
>         # (7 unchanged attributes hidden)
>     }
> 
>   # module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet has changed
>   ~ resource "azapi_resource" "subnet" {
>       ~ body                      = {
>           ~ properties = {
>               ~ routeTable                        = null -> {
>                   + id = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"
>                 }
>                 # (11 unchanged attributes hidden)
>             }
>         }
>         id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
>         name                      = "sea-prod-crawler-subnet"
>       ~ output                    = {
>           ~ etag       = "W/\"f5b2b34e-98be-440e-b523-496805063efa\"" -> "W/\"749db650-465f-4831-bd51-254baf47ed10\""
>             id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
>             # (2 unchanged attributes hidden)
>         }
>         # (6 unchanged attributes hidden)
>     }
> 
> 
> Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.      
> 
> ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   ~ update in-place
>  <= read (data resources)
> 
> Terraform will perform the following actions:
> 
>   # module.routetable["crawler"].data.azurerm_client_config.telemetry[0] will be read during apply
>   # (depends on a resource or a module with changes pending)
>  <= data "azurerm_client_config" "telemetry" {
>       + client_id       = (known after apply)
>       + id              = (known after apply)
>       + object_id       = (known after apply)
>       + subscription_id = (known after apply)
>       + tenant_id       = (known after apply)
>     }
> 
>   # module.routetable["crawler"].data.modtm_module_source.telemetry[0] will be read during apply
>   # (depends on a resource or a module with changes pending)
>  <= data "modtm_module_source" "telemetry" {
>       + module_path    = ".terraform/modules/routetable"
>       + module_source  = (known after apply)
>       + module_version = (known after apply)
>     }
> 
>   # module.routetable["crawler"].azurerm_route_table.this will be updated in-place
>   ~ resource "azurerm_route_table" "this" {
>       ~ bgp_route_propagation_enabled = true -> false
>         id                            = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"     
>         name                          = "sea-prod-crawler-rt"
>         tags                          = {}
>         # (5 unchanged attributes hidden)
>     }
> 
>   # module.routetable["crawler"].modtm_telemetry.telemetry[0] will be updated in-place
>   ~ resource "modtm_telemetry" "telemetry" {
>       + ephemeral_number = (known after apply)
>         id               = "8cba77cc-8301-41f9-9d5f-f39303488427"
>       + nonce            = (known after apply)
>       ~ tags             = {
>           ~ "module_source"   = "registry.terraform.io/Azure/avm-res-network-routetable/azurerm" -> (known after apply)
>           ~ "module_version"  = "0.3.1" -> (known after apply)
>             "random_id"       = "50b0928b-28ed-4bff-28df-d43508293e3d"
>           ~ "subscription_id" = "subs" -> (known after apply)
>           ~ "tenant_id"       = "tenant" -> (known after apply)
>         }
>     }
> 
>   # module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet will be updated in-place
>   ~ resource "azapi_resource" "subnet" {
>       ~ body                      = {
>           ~ properties = {
>               ~ routeTable                        = {
>                   - id = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt"
>                 } -> null
>                 # (11 unchanged attributes hidden)
>             }
>         }
>         id                        = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
>         name                      = "sea-prod-crawler-subnet"
>       ~ output                    = {
>           - etag       = "W/\"749db650-465f-4831-bd51-254baf47ed10\""
>           - id         = "/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet"
>           - properties = {
>               - provisioningState = "Succeeded"
>             }
>           - type       = "Microsoft.Network/virtualNetworks/subnets"
>         } -> (known after apply)
>         # (6 unchanged attributes hidden)
>     }
> 
> Plan: 0 to add, 3 to change, 0 to destroy.
> module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet: Modifying... [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet]
> module.virtualnetwork["sea-prod-crawler-vnet"].module.subnet["crawler"].azapi_resource.subnet: Modifications complete after 6s [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/virtualNetworks/sea-prod-crawler-vnet/subnets/sea-prod-crawler-subnet]
> module.routetable["crawler"].data.azurerm_client_config.telemetry[0]: Reading...
> module.routetable["crawler"].data.modtm_module_source.telemetry[0]: Reading...
> module.routetable["crawler"].data.azurerm_client_config.telemetry[0]: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD1kMTQ4MTM4NS05YzJkLTRmY2YtYjEwNy0zNmJkMzdlZDgxMGQ7b2JqZWN0SWQ9NWI4Zjg3YjctYTMwYy00ZGU0LWFjMzUtYzdjOTdhZDg5NTk0O3N1YnNjcmlwdGlvbklkPTRmNTc4ZTdmLWY1ZGMtNGQxZi05MDkyLWQ3NDkwZGFhNzM0Mzt0ZW5hbnRJZD0zNzNlOTBkMi1kOWEzLTQzYjUtODMyZS1jOGU5ODQ3YTc5Zjg=]
> module.routetable["crawler"].azurerm_route_table.this: Modifying... [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt]
> module.routetable["crawler"].data.modtm_module_source.telemetry[0]: Read complete after 0s
> module.routetable["crawler"].azurerm_route_table.this: Modifications complete after 4s [id=/subscriptions/subs/resourceGroups/sea-prod-crawler-network-rg/providers/Microsoft.Network/routeTables/sea-prod-crawler-rt]
> ```
Found out that link route table > vnet make terraform see changes outside terraform.
the way to fix is to attach the vnet subnet to route table instead other way

**Comment by jaredfholgate** [comment]
Further to this @oocx. I beleive that setting `disable_default_output` in your provider block will help here since this is default behaviour for azapi v2: https://registry.terraform.io/providers/Azure/azapi/latest/docs#disable_default_output-1.

This is not something we can set in the module, but you can set it in your root module.

**Comment by jaredfholgate** [comment]
I'll close this issue for now given it is standard behaviour with azapi v2. We'll need to decide more generally if it needs to be tackled on a module by module basis, so will take to the core team as a question.
