### ISSUE TITLE
resource alignment with CARML & AVM standards

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#22]
Quoting module guidance
> Resource modules: resource modules .... MUST mapped 1:1 to RPs (resource providers) and top level resources

for the ```Microsoft.Network/virtualNetworks``` resource provider, this means supporting the virtual network resource and the following child resources:
* ```Microsoft.Network/virtualNetworks/subnets```
* ```Microsoft.Network/virtualNetworks/virtualNetworkPeerings```

The ddos network protection plan doesn't fit in this hierarchy, should it be in this module?   (I'm aware it is conditionally created and you can just supply the DDOS plan id).

All said, however separating it out is likely to break the following guidance:

>Resource modules: resource modules have bring extra value to the end user (can’t just be simple wrappers) 

.. so I"m interested to hear AVM core team feedback on how best to approach that.

Currently, Bicep in CARML aligns to the resource provider mapping and treats the ddos protection plan as a separate resource, and alignment to Bicep is desirable, 

ref: https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr21---category-publishing---cross-language-collaboration

**Comment by herms14** [comment]
happy to align with what the CARML implementation. 

@Azure/avm-core-team would like to hear your thoughts on this feedback?

**Comment by AlexanderSehr** [comment]
Regarding subsets and peering yes, that would be ideal (including the optional reverse peering). DDOS protection I can bring up with the team. Strongly correlated services are usually also ok (like A NIC for a VM, or public IP for a firewall).

**Comment by herms14** [comment]
got it. Thanks! will remove the DDOS capability then.

**Comment by tanvp112** [comment]
`...accepting it as an optional input`

Please don't remove but let us have the option to enable/disable it.

**Comment by herms14** [comment]
This has been fixed in PR #20
