### ISSUE TITLE
Subnet should be optional attribute

### ISSUE THREAD

**Issue by cshea-msft** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#39]
Subnets is an optional attribute in Terraforms Registry so it should be an optional attribute in this module. Users might want to use Subnets in a separate module https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet

**Comment by herms14** [comment]
thanks for the feedback @cshea-msft. This will be addressed on the next PR

**Comment by herms14** [comment]
Hi @cshea-msft .

This has been resolved in the latest PR #54
