### ISSUE TITLE
[AVM Module Issue]: Location is set in variables as optional (default = null), but it is required by the module

### ISSUE THREAD

**Issue by bryansan-msft** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#58]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.1.4

### Description

Title says it all. It should default to the resource group if it is not specified as per AVM guidelines

![image](https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/assets/117635118/e18068cd-f727-41af-baf8-a7ddee368b2d)

**Comment by herms14** [comment]
Hi @bryansan-msft ,


Thanks for the feedback. I have resolved this issue by removing the null value on the location variable.
