### ISSUE TITLE
[AVM Module Issue]: 

### ISSUE THREAD

**Issue by phx-tim-butters** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#60]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.4

### Description

The current AVM for Virtual Networks creates the NSG association outside of the Virtual Network object. This requires two seperate calls to the API to create the Subnet NSG association.

A standard policy within the ALZ best practice is to Deny subnet creation that do not contain a Network Security Group association. Therefore when creating Virtual Networks with this AVM, along side the AVM for an ALZ Landing Zone deployment, the deployment fails due to Policy Violation.

A Policy enforcing Route Table isn't enforced as part of an ALZ deployment - and so a fix to this would be to create a Dynamic block within the Virtual Network block defining the subnets along side their NSG association. This will circumvent the Policy violation.

The association of Route Tables can remain it's own resource.

**Comment by herms14** [comment]
@Azure/avm-core-team need your inputs on this feedback

**Comment by ChrisSidebotham** [comment]
@mbilalamjad - Is this on your radar?

**Comment by haflidif** [comment]
@phx-tim-butters and @ChrisSidebotham this issue can be closed as it has been fixed and released in [v0.2.0](https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/releases/tag/v0.2.0) 

You agree @jaredfholgate , @matt-FFFFFF and @herms14 ?

**Comment by jaredfholgate** [comment]
> @phx-tim-butters and @ChrisSidebotham this issue can be closed as it has been fixed and released in [v0.2.0](https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/releases/tag/v0.2.0)
> 
> You agree @jaredfholgate , @matt-FFFFFF and @herms14 ?

Yes, agree that we have a solution now. Thanks again for raising this.
