### ISSUE TITLE
[AVM Module Issue]: Usage of a var instead of a local

### ISSUE THREAD

**Issue by ross-bohr** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#61]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.4

### Description

main.telemetry.tf uses the local enable_telemetry on line 2 and then uses the var with same name on line 10. This seems like a typo (something forgotten) and it is confusing. Is that the desired state or should it really be a reference to the local on line 10 as well?

**Comment by herms14** [comment]
@ross-bohr , 

Thanks for the checking! I replaced it to use the var instead and will be available on this PR #62

**Comment by herms14** [comment]
this has been resolved and will be available on the next PR
