### ISSUE TITLE
[AVM Module Issue]: VNet-Injection using azurerm_databricks_workspace causing: SubnetIsNotWithinVnetError Subnet CIDR range '<null>' is not within the Virtual Network CIDR range

### ISSUE THREAD

**Issue by Dipak-Mistry-WTW** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#97]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

Latest

### Description

The subnets are not getting created properly.  When trying to use the databricks avm I cannot create the workspaces due to error.  I first created the issue against the databricks AVM but it looks like I was incorrect and it looks like an issue with azapi creation of subnets by this module.

See https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/issues/46 for more details.

**Comment by jaredfholgate** [comment]
Released in 0.3.0. Use the address_prefix variable instead of the address_prefixes variable for cases like this.

**Comment by Dipak-Mistry-WTW** [comment]
I have just created a new environment using this module and I am still getting the same error:

```
│ Error: creating/updating Workspace (Subscription: "*******"
│ Resource Group Name: "********-rgrp"
│ Workspace Name: "*********-dbx"): polling after CreateOrUpdate: polling failed: the Azure API returned the following error:
│
│ Status: "SubnetIsNotWithinVnetError"
│ Code: ""
│ Message: "The subnet privates CIDR range '<null>' is not within the Virtual Network CIDR range '172.16.8.0/24'"
│ Activity Id: ""
│
│ ---
│
│ API Response:
│
│ ----[start]----
│ {
│   "status": "Failed",
│   "error": {
│     "code": "SubnetIsNotWithinVnetError",
│     "message": "The subnet privates CIDR range '<null>' is not within the Virtual Network CIDR range '172.16.8.0/24'"
│   }
│ }
│ -----[end]-----
```

However if I import an existing vnet (that was created prior to using the azapi resource provider) everything works as expected.

**Comment by jaredfholgate** [comment]
Apologies for not replying sooner, I have been out of office. Did you use the `address_prefix` variable and it still doesn't work? Can you share your latest code so that we can replicate this?

**Comment by jaredfholgate** [comment]
@Dipak-Mistry-WTW I see over here you mention you used the AddressPrefix field instead of AddressPrefixes. Did that solve it for you? https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/issues/46#issuecomment-2291427937

**Comment by Dipak-Mistry-WTW** [comment]
@jaredfholgate  - Yes I did use the address prefix field instead and yes it did work.  Although I remember it being difficult to switch  so it involved a bit of state manipulation. But I can't quite remember what the actual issue with switching from one to the other actually was.
