### ISSUE TITLE
[AVM Question/Feedback]: Migrating from v0.1.x to v0.2.x

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#98]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Is there any advice/guidance around migrating to version 0.2.x of this module due to the breaking changes? i.e. what can be done to avoid having to destroy and redeploy the virtual network, subnets, and peering?

This might be a good piece of documentation for early adopters of this module.

Thanks, appreciate the support.

**Comment by matt-FFFFFF** [comment]
Hi!

With this sort of change I'd recommend leaving your existing resources on the old version and deploying new ones with the new version.

If you want to migrate you can use import/removed {} blocks to achieve this.

We will provide documentation on how to do this.

**Comment by captainhook** [comment]
@matt-FFFFFF thank you very much! Is there any general guidance available yet on using import blocks with AVM?

For example, if I use:
```
import {
  to = module.virtual_network.azurerm_virtual_network.vnet
  id = "/subscriptions/xxx/resourceGroups/rg-IdentityConnectivity-prod-001/providers/Microsoft.Network/virtualNetworks/vnet-IdentityConnectivity-prod-001"
}
```

I get the following error:
`The configuration for the given import target module.virtual_network.azurerm_virtual_network.vnet does not exist. All target instances must have an associated configuration to be imported.`

I appreciate this is perhaps more of a general Terraform question.

**Comment by captainhook** [comment]
I managed to figure it out, it should've been:

```
removed {
  from = module.virtual_network.azurerm_virtual_network.vnet
  lifecycle {
    destroy = false
  }
}
import {
  to = module.virtual_network.azapi_resource.vnet
  id = "/subscriptions/xxx/resourceGroups/rg-IdentityConnectivity-prod-001/providers/Microsoft.Network/virtualNetworks/vnet-IdentityConnectivity-prod-001"
}
```
